### PR TITLE
add basic oasis support Refs #1

### PR DESCRIPTION
**Pull request by little-arhat**

### CODE REVIEW

**Comment by little-arhat** [comment]
It's very good and right idea to start new ocaml project with oasis as helper tool. With simple `_oasis` file you can get autogenerated `_tags`, `myocamlbuild.ml`, `Makefile` and other tools for easier running and installing library/application on other machines.

**Comment by wickedchicken** [comment]
Very cool, thanks for this -- I'll take a more in-depth view tonight.

**Comment by little-arhat** [comment]
Hi, what about this pull request?

**Comment by wickedchicken** [comment]
Hey, sorry about leaving this for so long. I was hesitant to add auto-generated output to a project I was hoping to keep simple and understandable without external tooling. I should have responded earlier, but drifted away from the OCaml community due to life circumstances. I'm in the process of archiving this repo and will close this PR as such, but thank you for contributing anyway.

**Pull request closed without merging**
